//go:build e2e

package constellation

// Tier-A E2E harness: a multi-process constellation over loopback.
//
// Each "node" is a re-exec of this test binary (TestE2ENodeMain in
// e2e_nodemain_test.go) with its own CONFIGFOLDER and a distinct 127.0.1.x
// address standing in for its nebula mesh IP. The embedded NATS servers,
// JetStream, leafnode topology, device DB, sync protocol and DNS all run for
// real; only the nebula binary is a stub (a sleep loop), which still
// exercises the full process-supervision path (PID files, monitor goroutine,
// restarts). Enrollment uses the real DeviceCreate + getYAMLClientConfig.
//
// Run with:
//   go test -race -tags e2e -run TestE2E -timeout 30m ./src/constellation/

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"testing"
	"time"

	"github.com/azukaar/cosmos-server/src/utils"
)

const e2eControlPort = 47901

type e2eNodeSpec struct {
	Name       string
	Octet      int // node IP = 127.0.1.<Octet>
	CosmosNode int // 2 = manager, 1 = agent
	Agent      bool
	Lighthouse bool
}

type e2eNode struct {
	spec      e2eNodeSpec
	ip        string
	configDir string // trailing slash
	workDir   string
	logPath   string
	cmd       *exec.Cmd
	waitCh    chan error
}

type e2eCluster struct {
	t     *testing.T
	root  string
	ha    bool
	nodes map[string]*e2eNode

	// kept from bootstrap so nodes provisioned later (enrollVia) get the same
	// self-signed cert as the rest of the cluster's NATS TLS listeners
	tlsCert string
	tlsKey  string

	// each node's NATS password, by device name. Fencing scenarios need to dial a
	// survivor with a fenced node's identity, which is the only direct way to ask
	// whether its credentials are actually dead.
	apiKeys map[string]string
}

func (n *e2eNode) controlURL() string {
	return fmt.Sprintf("http://%s:%d", n.ip, e2eControlPort)
}

// newE2ECluster provisions config folders for every node and enrolls every
// device through the real creation path, mirroring production: the first spec
// is the constellation creator (must be a manager + lighthouse); every other
// node receives a device config generated by getYAMLClientConfig. Nothing is
// started yet — tests control startup order.
func newE2ECluster(t *testing.T, ha bool, specs []e2eNodeSpec) *e2eCluster {
	t.Helper()

	if specs[0].CosmosNode != 2 || !specs[0].Lighthouse {
		t.Fatal("e2e: first spec must be the creator (manager + lighthouse)")
	}

	requireFreeControlPorts(t, specs)

	c := &e2eCluster{t: t, root: t.TempDir(), ha: ha,
		nodes: map[string]*e2eNode{}, apiKeys: map[string]string{}}

	for _, s := range specs {
		c.provision(s)
	}

	c.bootstrap(specs)

	t.Cleanup(func() {
		for _, n := range c.nodes {
			n.killSilent()
		}
		// after the nodes, because a live node would just respawn its stub
		c.reapNebulaStubs()
		c.scanLogs()
		if t.Failed() {
			c.preserveLogs()
		}
	})

	return c
}

// provision lays down a node's directories and fake nebula work dir. It does
// NOT enroll the node — bootstrap does that for the initial set, enrollVia for
// nodes that join a running cluster later.
func (c *e2eCluster) provision(s e2eNodeSpec) *e2eNode {
	c.t.Helper()
	n := &e2eNode{
		spec:      s,
		ip:        fmt.Sprintf("127.0.1.%d", s.Octet),
		configDir: filepath.Join(c.root, s.Name, "config") + "/",
		workDir:   filepath.Join(c.root, s.Name, "work"),
		logPath:   filepath.Join(c.root, s.Name, "node.log"),
	}
	if err := os.MkdirAll(n.configDir, 0755); err != nil {
		c.t.Fatal("e2e: mkdir config:", err)
	}
	writeFakeNebulaWorkDir(c.t, n.workDir)
	c.nodes[s.Name] = n
	return n
}

// enrollVia provisions a brand-new node and enrolls it through a LIVE node's
// control API, rather than in the parent process the way bootstrap does.
//
// This is the only faithful way to test a replacement manager joining after a
// force-reform: enrollment has to run on the survivor, in formation mode,
// against the survivor's own post-reform device table and its new epoch.
// Enrolling in the parent would bypass exactly the code the scenario is about.
func (c *e2eCluster) enrollVia(enroller string, s e2eNodeSpec) {
	c.t.Helper()

	if _, exists := c.nodes[s.Name]; exists {
		c.t.Fatal("e2e: node already provisioned: " + s.Name)
	}
	if c.tlsCert == "" {
		c.t.Fatal("e2e: cluster has no stored TLS cert; bootstrap did not run")
	}

	// Retried rather than one-shot: the enroller may be inside a mesh bounce from
	// its own previous write. Every attempt is logged, so an enrollment that only
	// works on the fourth try still shows up as a problem instead of being hidden.
	var out map[string]interface{}
	var err error
	deadline := time.Now().Add(90 * time.Second)
	for attempt := 1; ; attempt++ {
		out, err = c.node(enroller).post("/enroll", map[string]interface{}{
			"DeviceName":   s.Name,
			"IP":           fmt.Sprintf("127.0.1.%d", s.Octet),
			"CosmosNode":   s.CosmosNode,
			"IsLighthouse": s.Lighthouse,
		})
		if err == nil {
			if attempt > 1 {
				c.t.Logf("e2e: enroll %s via %s succeeded on attempt %d", s.Name, enroller, attempt)
			}
			break
		}
		c.t.Logf("e2e: enroll %s via %s attempt %d failed: %v", s.Name, enroller, attempt, err)
		if time.Now().After(deadline) {
			c.t.Fatalf("e2e: enroll %s via %s: %v", s.Name, enroller, err)
		}
		time.Sleep(3 * time.Second)
	}
	yml, _ := out["nebulaYml"].(string)
	if yml == "" {
		c.t.Fatalf("e2e: enroll %s via %s returned no nebula config", s.Name, enroller)
	}
	if key, ok := out["apiKey"].(string); ok {
		c.apiKeys[s.Name] = key
	}

	n := c.provision(s)
	if err := os.WriteFile(n.configDir+"nebula.yml", []byte(yml), 0600); err != nil {
		c.t.Fatal("e2e: write enrolled nebula.yml:", err)
	}

	// the node's own main config, written the same way bootstrap writes the
	// non-creator ones
	prevFolder := utils.CONFIGFOLDER
	defer func() {
		utils.CONFIGFOLDER = prevFolder
		utils.CloseStore()
	}()
	utils.CONFIGFOLDER = n.configDir
	utils.SetBaseMainConfig(c.nodeConfig(s, c.tlsCert, c.tlsKey))
}

// bootstrap runs the creator-side enrollment inside the parent test process:
// CA generation, one DeviceCreate per node, and device config YAML generation
// for every non-creator node. Package globals touched here are restored.
func (c *e2eCluster) bootstrap(specs []e2eNodeSpec) {
	t := c.t
	t.Helper()

	prevFolder := utils.CONFIGFOLDER
	prevFBL := utils.FBL
	defer func() {
		utils.CONFIGFOLDER = prevFolder
		utils.FBL = prevFBL
		// close with no reopen (faithful port of the old CloseEmbeddedDB): the parent
		// has no use for a store after bootstrap, and prevFolder is the package default
		// /var/lib/cosmos/, which does not exist under test
		utils.CloseStore()
		resetConstellationGlobals()
	}()

	// lift community node limits so we can enroll multiple managers/agents;
	// the dead URL guarantees no licence traffic can leave the process
	utils.FBL = utils.NewFirebaseApiSdk("http://127.0.0.1:9")
	utils.FBL.LValid = true
	utils.FBL.CosmosNodeNumber = 100
	utils.FBL.UserNumber = 100

	chdirWithCertBinary(t)

	// one self-signed web cert shared by every node (NATS TLS listeners)
	scratch := t.TempDir() + "/"
	utils.CONFIGFOLDER = scratch
	utils.LoadBaseMainConfig(utils.DefaultConfig)
	tlsCert, tlsKey, err := utils.GenerateRSAWebCertificates([]string{"cosmos-e2e.local"})
	if err != nil {
		t.Fatal("e2e: generate TLS cert:", err)
	}
	c.tlsCert, c.tlsKey = tlsCert, tlsKey

	creator := c.nodes[specs[0].Name]
	utils.CONFIGFOLDER = creator.configDir
	utils.SetBaseMainConfig(c.nodeConfig(specs[0], tlsCert, tlsKey))

	// DeviceCreate below writes through the store, which must point at the creator dir
	if err := utils.InitStore(); err != nil {
		t.Fatal("e2e: InitStore creator:", err)
	}

	// The creator takes the formation write licence, exactly as the real creation
	// handler does (API_NewConstellation, api_nebula_connect.go:142). This harness
	// bootstraps by calling DeviceCreate in the parent process instead of going
	// through that handler, so it has to grant the licence itself — and it is not
	// optional bookkeeping: ensureOplogStream refuses to create a stream for a node
	// that is neither the formation writer nor already materialized from the log
	// (oplog.go:330-336), so without this NO node is licensed to create the op-log
	// and every node waits for a formation writer that does not exist. Observed as
	// a whole HA cluster sitting at e1/0 with divergent dumps and no stream.
	if err := utils.SetFormationWriter(utils.GetOplogEpoch()); err != nil {
		t.Fatal("e2e: set formation writer on the creator:", err)
	}

	InitConfig()
	if err := generateNebulaCACert("cosmos-e2e"); err != nil {
		t.Fatal("e2e: generate CA:", err)
	}
	if err := ExportDefaultConfigToYAML(creator.configDir + "nebula.yml"); err != nil {
		t.Fatal("e2e: write creator nebula.yml:", err)
	}

	// enroll every device first so lighthouse lists and manager seeds are
	// complete when the per-device configs are generated
	type enrolled struct {
		cert, key string
		req       DeviceCreateRequestJSON
	}
	created := map[string]enrolled{}
	for _, s := range specs {
		cert, key, _, req, err := DeviceCreate(DeviceCreateRequestJSON{
			DeviceName:   s.Name,
			IP:           fmt.Sprintf("127.0.1.%d", s.Octet),
			IsLighthouse: s.Lighthouse,
			CosmosNode:   s.CosmosNode,
			Port:         "4242",
		})
		if err != nil {
			t.Fatal("e2e: DeviceCreate "+s.Name+":", err)
		}
		created[s.Name] = enrolled{cert: cert, key: key, req: req}
		c.apiKeys[s.Name] = req.APIKey
	}

	capki, err := getCApki()
	if err != nil {
		t.Fatal("e2e: read CA:", err)
	}

	// generate ALL device configs while the creator's main config is still
	// loaded: getYAMLClientConfig reads NATSReplicas from the live config to
	// stamp cstln_nats_ha, and only the creator's config carries it (this
	// mirrors production enrollment, which always runs on the creator here)
	for _, s := range specs[1:] {
		e := created[s.Name]
		yml, err := getYAMLClientConfig(s.Name, creator.configDir+"nebula.yml",
			capki, e.cert, e.key, e.req.APIKey, utils.ConstellationDevice{
				DeviceName:   s.Name,
				IP:           e.req.IP,
				IsLighthouse: s.Lighthouse,
				CosmosNode:   s.CosmosNode,
				Port:         "4242",
				APIKey:       e.req.APIKey,
			}, false, false)
		if err != nil {
			t.Fatal("e2e: getYAMLClientConfig "+s.Name+":", err)
		}
		n := c.nodes[s.Name]
		if err := os.WriteFile(n.configDir+"nebula.yml", []byte(yml), 0600); err != nil {
			t.Fatal("e2e: write nebula.yml:", err)
		}
	}

	// only after every YAML is generated, write each node's own main config
	for _, s := range specs[1:] {
		utils.CONFIGFOLDER = c.nodes[s.Name].configDir
		utils.SetBaseMainConfig(c.nodeConfig(s, tlsCert, tlsKey))
	}
}

func (c *e2eCluster) nodeConfig(s e2eNodeSpec, tlsCert, tlsKey string) utils.Config {
	cfg := utils.DefaultConfig
	cfg.NewInstall = false
	cfg.LoggingLevel = "INFO" // DEBUG would rebind NATS to 0.0.0.0 and collide across nodes
	cfg.MonitoringDisabled = true
	cfg.HTTPConfig.TLSCert = tlsCert
	cfg.HTTPConfig.TLSKey = tlsKey
	cfg.HTTPConfig.Hostname = fmt.Sprintf("127.0.1.%d", s.Octet)
	cfg.ConstellationConfig.Enabled = true
	cfg.ConstellationConfig.DNSPort = "15353"
	cfg.ConstellationConfig.DNSFallback = "8.8.8.8:53"
	cfg.ConstellationConfig.DNSAdditionalBlocklists = []string{}
	cfg.ConstellationConfig.IPRange = "127.0.1.0/24"
	cfg.ConstellationConfig.ConstellationHostname = "cosmos-e2e.local"
	if s.Name == c.creatorName() {
		cfg.ConstellationConfig.ThisDeviceName = s.Name
		if c.ha {
			cfg.ConstellationConfig.NATSReplicas = 3
		}
	}
	return cfg
}

// creatorName returns the constellation creator: by construction the only
// lighthouse manager (specs[0]).
func (c *e2eCluster) creatorName() string {
	for name, n := range c.nodes {
		if n.spec.CosmosNode == 2 && n.spec.Lighthouse {
			return name
		}
	}
	return ""
}

// writeFakeNebulaWorkDir creates the node's CWD: a fake `nebula` binary that
// just stays alive (the supervision code treats it as a healthy VPN process)
// plus symlinks to the real nebula-cert binaries.
func writeFakeNebulaWorkDir(t *testing.T, dir string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0755); err != nil {
		t.Fatal("e2e: mkdir work:", err)
	}
	script := "#!/bin/sh\ntrap 'exit 0' TERM INT\nwhile true; do sleep 3600; done\n"
	for _, name := range []string{"nebula", "nebula-arm"} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(script), 0755); err != nil {
			t.Fatal("e2e: write fake nebula:", err)
		}
	}
	root := repoRootDir(t)
	for _, bin := range []string{"nebula-cert", "nebula-arm-cert"} {
		src := filepath.Join(root, bin)
		if _, err := os.Stat(src); err == nil {
			os.Symlink(src, filepath.Join(dir, bin))
		}
	}
}

func (c *e2eCluster) node(name string) *e2eNode {
	n, ok := c.nodes[name]
	if !ok {
		c.t.Fatal("e2e: unknown node " + name)
	}
	return n
}

// start launches the node child process and waits for its control API.
func (c *e2eCluster) start(name string) {
	t := c.t
	t.Helper()
	n := c.node(name)
	if n.cmd != nil {
		t.Fatal("e2e: node already running: " + name)
	}

	logf, err := os.OpenFile(n.logPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		t.Fatal("e2e: open node log:", err)
	}

	cmd := exec.Command(os.Args[0], "-test.run=^TestE2ENodeMain$", "-test.v", "-test.timeout=0")
	cmd.Dir = n.workDir
	cmd.Stdout = logf
	cmd.Stderr = logf
	env := []string{}
	for _, kv := range os.Environ() {
		if strings.HasPrefix(kv, "CONFIG_FILE=") || strings.HasPrefix(kv, "COSMOS_") {
			continue
		}
		env = append(env, kv)
	}
	cmd.Env = append(env,
		"COSMOS_E2E_NODE=1",
		"COSMOS_E2E_CONFIGFOLDER="+n.configDir,
		"COSMOS_E2E_CONTROL_ADDR="+fmt.Sprintf("%s:%d", n.ip, e2eControlPort),
		fmt.Sprintf("COSMOS_E2E_AGENT=%v", n.spec.Agent),
	)
	if err := cmd.Start(); err != nil {
		t.Fatal("e2e: start node:", err)
	}
	n.cmd = cmd
	n.waitCh = make(chan error, 1)
	go func() {
		n.waitCh <- cmd.Wait()
		logf.Close()
	}()

	c.waitFor(60*time.Second, name+" control API up", func() bool {
		_, err := n.get("/status")
		return err == nil
	})
}

func (n *e2eNode) signal(sig syscall.Signal) error {
	if n.cmd == nil || n.cmd.Process == nil {
		return fmt.Errorf("node not running")
	}
	return n.cmd.Process.Signal(sig)
}

// kill SIGKILLs the node (crash simulation) and reaps it.
func (c *e2eCluster) kill(name string) {
	c.t.Helper()
	n := c.node(name)
	if err := n.signal(syscall.SIGKILL); err != nil {
		c.t.Fatal("e2e: kill:", err)
	}
	<-n.waitCh
	n.cmd = nil
}

func (n *e2eNode) killSilent() {
	if n.cmd != nil && n.cmd.Process != nil {
		n.cmd.Process.Kill()
		if n.waitCh != nil {
			select {
			case <-n.waitCh:
			case <-time.After(10 * time.Second):
			}
		}
		n.cmd = nil
	}
}

// freeze/thaw simulate a hung node (SIGSTOP keeps sockets open but nothing
// responds — a failure mode clean kills never produce).
func (c *e2eCluster) freeze(name string) {
	c.t.Helper()
	if err := c.node(name).signal(syscall.SIGSTOP); err != nil {
		c.t.Fatal("e2e: freeze:", err)
	}
}

func (c *e2eCluster) thaw(name string) {
	c.t.Helper()
	if err := c.node(name).signal(syscall.SIGCONT); err != nil {
		c.t.Fatal("e2e: thaw:", err)
	}
}
